/**
 * Feature flag framework — shared types (single source of truth is
 * config/features/registry.json; nothing here defines defaults).
 */

export type FeatureId = string;
export type SafetyClass = "safe" | "unsafe";

/** Deterministic reasons a feature is not effective. */
export type DisabledReason =
  | "NOT_BUILT"
  | "RUNTIME_DISABLED"
  | "PARENT_DISABLED"
  | "DEPENDENCY_DISABLED"
  | "INVALID_CONFIGURATION";

export interface FeatureDefinition {
  id: FeatureId;
  round: number;
  description: string;
  parent: FeatureId | null;
  dependencies: FeatureId[];
  buildDefault: boolean;
  runtimeDefault: boolean;
  safetyClass: SafetyClass;
  envBuildName: string;
  envRuntimeName: string;
}

export interface FeatureRegistry {
  registryVersion: string;
  features: FeatureDefinition[];
}

/** Immutable build-time manifest (generated by scripts/generate-feature-manifest.mts). */
export interface BuildFeatureManifest {
  buildProfile: string;
  registryVersion: string;
  generatedAt: string;
  buildFeatureHash: string;
  enabledFeatures: FeatureId[];
  disabledFeatures: FeatureId[];
  buildEnabled: Record<FeatureId, boolean>;
}

export interface FeatureState {
  id: FeatureId;
  buildEnabled: boolean;
  runtimeEnabled: boolean;
  effectiveEnabled: boolean;
  disabledReason: DisabledReason | null;
  parent: FeatureId | null;
  dependencies: FeatureId[];
}

export interface RuntimeResolvedConfig {
  /** resolved runtime profile id (null when none applied) */
  runtimeProfile: string | null;
  runtimeFeatureHash: string;
  runtimeEnabled: Record<FeatureId, boolean>;
}

/** Runtime configuration inputs. In production the resolver reads env +
 *  FEATURE_RUNTIME_CONFIG_PATH + FEATURE_RUNTIME_PROFILE; explicit values are
 *  used by tests, scripts and experiment drivers (never a second source of
 *  defaults). */
export interface RuntimeConfigInput {
  features?: Record<FeatureId, boolean>;
  experimentId?: string | null;
  runtimeProfile?: string | null;
  modelId?: string | null;
  promptVersion?: string | null;
  datasetSnapshot?: string | null;
  randomSeed?: string | null;
  ruleVersion?: string | null;
}

/** Reproducibility record — every evaluation run references effectiveFeatureHash. */
export interface FeatureSnapshot {
  experimentId: string | null;
  commitSha: string;
  buildProfile: string;
  buildFeatureHash: string;
  runtimeProfile: string | null;
  runtimeFeatureHash: string;
  effectiveFeatureHash: string;
  effectiveFeatures: FeatureId[];
  disabledFeatures: FeatureId[];
  unsafeAblations: FeatureId[];
  modelId: string | null;
  promptVersion: string | null;
  datasetSnapshot: string | null;
  randomSeed: string | null;
  ruleVersion: string;
  generatedAt: string;
}

export interface FeatureResolver {
  isBuilt(id: FeatureId): boolean;
  isRuntimeEnabled(id: FeatureId): boolean;
  isEffective(id: FeatureId): boolean;
  /** Throws when the feature is not effective (used by internal components). */
  requireFeature(id: FeatureId): void;
  getFeatureState(id: FeatureId): FeatureState;
  getEffectiveFeatureSnapshot(opts?: RuntimeConfigInput): FeatureSnapshot;
  getStates(): Record<FeatureId, FeatureState>;
  getBuildManifest(): BuildFeatureManifest;
  getRuntimeProfile(): string | null;
  /** Non-fatal configuration notes (e.g. unsafe ablation requested without EVALUATION_MODE). */
  getWarnings(): string[];
}

export const DISABLED_REASONS: readonly DisabledReason[] = [
  "NOT_BUILT",
  "RUNTIME_DISABLED",
  "PARENT_DISABLED",
  "DEPENDENCY_DISABLED",
  "INVALID_CONFIGURATION",
];
