/**
 * Generate the immutable build feature manifests (single registry.json input).
 *
 * Usage:
 *   node --experimental-strip-types scripts/generate-feature-manifest.mts
 *
 * Selection:
 *   FEATURE_BUILD_PROFILE=full|baseline|multimodal-only|lakehouse-only|evaluation-full
 *     (default: full) — or an explicit profile file:
 *   FEATURE_BUILD_CONFIG_PATH=/path/to/profile.json
 *
 * Build-time overrides: any BUILD_* / BUILD_UNSAFE_EVALUATION_ABLATIONS env
 * matching a registry envBuildName. Unsafe ablations are ONLY compiled when
 * BUILD_UNSAFE_EVALUATION_ABLATIONS=true (dual gate is completed at runtime).
 *
 * Outputs (all express the same switch state):
 *   src/generated/build-features.ts
 *   services/lakehouse-gateway/app/generated/build_features.py
 *   build/feature-manifest.json
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { featureHash } from "../src/features/hash.ts";
import { loadFeatureRegistry } from "../src/features/registry.ts";
import type { BuildFeatureManifest, FeatureId } from "../src/features/types.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const REGISTRY_PATH = join(ROOT, "config", "features", "registry.json");
const PROFILES_DIR = join(ROOT, "config", "features", "build-profiles");

interface BuildProfileFile {
  buildProfile: string;
  features?: Record<string, boolean>;
}

function resolveProfile(): { name: string; features: Record<string, boolean> } {
  const explicitPath = process.env.FEATURE_BUILD_CONFIG_PATH;
  const profileName = process.env.FEATURE_BUILD_PROFILE ?? "full";
  let profile: BuildProfileFile;
  if (explicitPath) {
    profile = JSON.parse(readFileSync(explicitPath, "utf8")) as BuildProfileFile;
  } else {
    const path = join(PROFILES_DIR, `${profileName}.json`);
    try {
      profile = JSON.parse(readFileSync(path, "utf8")) as BuildProfileFile;
    } catch {
      throw new Error(
        `build profile '${profileName}' not found (${path}). ` +
          `FEATURE_BUILD_PROFILE must be one of: full, baseline, multimodal-only, lakehouse-only, evaluation-full ` +
          `(or pass FEATURE_BUILD_CONFIG_PATH)`,
      );
    }
  }
  return { name: profile.buildProfile, features: profile.features ?? {} };
}

function parseBool(v: string | undefined): boolean | undefined {
  if (v === "true") return true;
  if (v === "false") return false;
  return undefined;
}

function main(): void {
  const registry = loadFeatureRegistry(REGISTRY_PATH);
  const { name: profileName, features: profile } = resolveProfile();
  const unsafeMaster = parseBool(process.env.BUILD_UNSAFE_EVALUATION_ABLATIONS) ?? false;

  const buildEnabled: Record<FeatureId, boolean> = {};
  for (const f of registry.features) {
    let value = profile[f.id] ?? f.buildDefault;
    // env overrides (BUILD_*)
    const envValue = parseBool(process.env[f.envBuildName]);
    if (envValue !== undefined) value = envValue;
    // unsafe ablations: dual gate at build time — master env required
    if (f.safetyClass === "unsafe" && !unsafeMaster) value = false;
    buildEnabled[f.id] = value;
  }

  const enabledFeatures = registry.features.filter((f) => buildEnabled[f.id]).map((f) => f.id).sort();
  const disabledFeatures = registry.features.filter((f) => !buildEnabled[f.id]).map((f) => f.id).sort();
  const generatedAt = new Date().toISOString();
  const buildFeatureHash = featureHash({
    registryVersion: registry.registryVersion,
    buildProfile: profileName,
    buildEnabled,
  });

  const manifest: BuildFeatureManifest = {
    buildProfile: profileName,
    registryVersion: registry.registryVersion,
    generatedAt,
    buildFeatureHash,
    enabledFeatures,
    disabledFeatures,
    buildEnabled,
  };

  writeTypeScript(manifest);
  writePython(manifest);
  writeJson(manifest);
  // eslint-disable-next-line no-console
  console.log(
    `[features] build manifest generated: profile=${profileName} registry=${registry.registryVersion} ` +
      `enabled=${enabledFeatures.length} disabled=${disabledFeatures.length} hash=${buildFeatureHash}`,
  );
}

function writeTypeScript(m: BuildFeatureManifest): void {
  const path = join(ROOT, "src", "generated", "build-features.ts");
  const body = JSON.stringify(m, null, 2);
  const content = `/**
 * GENERATED by scripts/generate-feature-manifest.mts — DO NOT EDIT.
 * Regenerate with: node --experimental-strip-types scripts/generate-feature-manifest.mts
 * Source of truth: config/features/registry.json + config/features/build-profiles/*.json
 */
import type { BuildFeatureManifest } from "../features/types.ts";

export const BUILD_FEATURE_MANIFEST: BuildFeatureManifest = ${body} as const;
`;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
}

function pyBool(value: boolean): string {
  return value ? "True" : "False";
}

function writePython(m: BuildFeatureManifest): void {
  const path = join(ROOT, "services", "lakehouse-gateway", "app", "generated", "build_features.py");
  const buildEnabled = Object.entries(m.buildEnabled)
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([id, v]) => `    "${id}": ${pyBool(v)},`)
    .join("\n");
  const content = `"""GENERATED by scripts/generate-feature-manifest.mts — DO NOT EDIT.

Regenerate with:
    node --experimental-strip-types scripts/generate-feature-manifest.mts

Source of truth: config/features/registry.json + config/features/build-profiles/*.json
"""

BUILD_FEATURE_MANIFEST = {
    "buildProfile": "${m.buildProfile}",
    "registryVersion": "${m.registryVersion}",
    "generatedAt": "${m.generatedAt}",
    "buildFeatureHash": "${m.buildFeatureHash}",
    "enabledFeatures": [${m.enabledFeatures.map((id) => `"${id}"`).join(", ")}],
    "disabledFeatures": [${m.disabledFeatures.map((id) => `"${id}"`).join(", ")}],
    "buildEnabled": {
${buildEnabled}
    },
}
`;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
}

function writeJson(m: BuildFeatureManifest): void {
  const path = join(ROOT, "build", "feature-manifest.json");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(m, null, 2)}\n`, "utf8");
}

main();
