"""Feature flag framework for the lakehouse gateway (Python side).

Single source of truth: config/features/registry.json at the PoC root.
The build manifest (app/generated/build_features.py) is generated by
scripts/generate-feature-manifest.mts and is immutable at runtime.

Runtime resolution priority (per spec):
    1. environment variable explicit override
    2. FEATURE_RUNTIME_CONFIG_PATH config file
    3. runtime profile (FEATURE_RUNTIME_PROFILE or config file runtimeProfile)
    4. registry.json runtimeDefault

effectiveEnabled = buildEnabled AND runtimeEnabled AND parentEnabled AND
dependenciesEnabled. Runtime can never enable a feature the build manifest
excluded.

Unsafe ablations (safetyClass=unsafe) need the full dual gate:
BUILD_UNSAFE_EVALUATION_ABLATIONS=true (build) + EVALUATION_MODE=true +
APP_ENV != production (runtime); APP_ENV=production with any unsafe
configuration refuses to start.

CLI:
    python -m app.features --print [--json] [--write]

Environment variables are ONLY read in this module (and the generator).
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional, Union

from app.generated.build_features import BUILD_FEATURE_MANIFEST

# ruleVersion reported in snapshots — must match cdxr-engine ASSESSMENT_RULE_VERSION
CDXR_RULE_VERSION = "cdxr-training.v1"

# Legacy env aliases honored centrally (never read outside this module).
ENV_ALIASES: dict[str, list[str]] = {
    "ENABLE_CDXR_TRAINING_TOOL": ["round3.cdxr_training"],
    "ENABLE_LEGACY_CDXR_GOVERNANCE": ["legacy.cdxr_governance_cli", "legacy.cdxr_governance_tools"],
}

UNSAFE_MASTER_BUILD_ENV = "BUILD_UNSAFE_EVALUATION_ABLATIONS"
EVALUATION_MODE_ENV = "EVALUATION_MODE"
APP_ENV_VAR = "APP_ENV"
STRICT_ENV = "FEATURE_CONFIG_STRICT"
RUNTIME_PROFILE_ENV = "FEATURE_RUNTIME_PROFILE"
RUNTIME_CONFIG_PATH_ENV = "FEATURE_RUNTIME_CONFIG_PATH"

DISABLED_REASONS = ("NOT_BUILT", "RUNTIME_DISABLED", "PARENT_DISABLED", "DEPENDENCY_DISABLED", "INVALID_CONFIGURATION")


def _config_dir() -> Path:
    return Path(__file__).resolve().parents[3] / "config" / "features"


def _parse_bool(value: Optional[Union[str, bool]]) -> Optional[bool]:
    """Parse a feature switch: already-bool JSON values pass through, strings
    are accepted as "true"/"false" (env values). Anything else → None (no
    override)."""
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if value == "true":
        return True
    if value == "false":
        return False
    return None


def _canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def feature_hash(value: Any) -> str:
    """First 16 hex chars of sha256 over canonical JSON — identical to TS."""
    return hashlib.sha256(_canonical_json(value).encode("utf-8")).hexdigest()[:16]


def load_registry(path: Optional[Path] = None) -> dict[str, Any]:
    """Load config/features/registry.json and validate it."""
    registry_path = path or (_config_dir() / "registry.json")
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    ids = {f["id"] for f in registry["features"]}
    for f in registry["features"]:
        if f["parent"] is not None and f["parent"] not in ids:
            raise ValueError(f"feature {f['id']}: parent '{f['parent']}' is not defined")
        for dep in f["dependencies"]:
            if dep not in ids:
                raise ValueError(f"feature {f['id']}: dependency '{dep}' is not defined")
        if f["safetyClass"] not in ("safe", "unsafe"):
            raise ValueError(f"feature {f['id']}: invalid safetyClass '{f['safetyClass']}'")
    return registry


@dataclass
class FeatureState:
    id: str
    buildEnabled: bool
    runtimeEnabled: bool
    effectiveEnabled: bool
    disabledReason: Optional[str]
    parent: Optional[str]
    dependencies: list[str]

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "buildEnabled": self.buildEnabled,
            "runtimeEnabled": self.runtimeEnabled,
            "effectiveEnabled": self.effectiveEnabled,
            "disabledReason": self.disabledReason,
            "parent": self.parent,
            "dependencies": list(self.dependencies),
        }


@dataclass
class RuntimeResolved:
    runtime_profile: Optional[str] = None
    runtime_enabled: dict[str, bool] = field(default_factory=dict)
    experiment_id: Optional[str] = None
    warnings: list[str] = field(default_factory=list)
    config_errors: list[str] = field(default_factory=list)


@dataclass
class FeatureSnapshot:
    experimentId: Optional[str]
    commitSha: str
    buildProfile: str
    buildFeatureHash: str
    runtimeProfile: Optional[str]
    runtimeFeatureHash: str
    effectiveFeatureHash: str
    effectiveFeatures: list[str]
    disabledFeatures: list[str]
    unsafeAblations: list[str]
    modelId: Optional[str]
    promptVersion: Optional[str]
    datasetSnapshot: Optional[str]
    randomSeed: Optional[str]
    ruleVersion: str
    generatedAt: str

    def to_dict(self) -> dict[str, Any]:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}  # noqa: E501


def resolve_runtime_settings(registry: dict[str, Any],
                             env: Optional[dict[str, str]] = None,
                             runtime_input: Optional[dict[str, Any]] = None) -> RuntimeResolved:
    """Resolve runtime enablement: defaults < runtime profile < config file < env."""
    env = os.environ if env is None else env
    runtime_input = runtime_input or {}
    defs = {f["id"]: f for f in registry["features"]}
    warnings: list[str] = []
    config_errors: list[str] = []

    enabled: dict[str, bool] = {f["id"]: f["runtimeDefault"] for f in registry["features"]}

    # 1) runtime profile (lowest explicit layer)
    config_file: dict[str, Any] = {}
    config_path = env.get(RUNTIME_CONFIG_PATH_ENV)
    if config_path:
        config_file = json.loads(Path(config_path).read_text(encoding="utf-8"))
    file_features = config_file.get("features", {})
    file_profile_name = config_file.get("runtimeProfile")
    profile_name = (runtime_input.get("runtimeProfile")
                    or file_profile_name
                    or env.get(RUNTIME_PROFILE_ENV)
                    or None)

    if profile_name is not None:
        profile = json.loads(
            (_config_dir() / "runtime-profiles" / f"{profile_name}.json").read_text(encoding="utf-8"))
        for fid, value in profile.get("features", {}).items():
            if fid not in defs:
                config_errors.append(f"runtime profile '{profile_name}' references unknown feature '{fid}'")
                continue
            parsed = _parse_bool(value if isinstance(value, bool) else None)
            if parsed is not None:
                enabled[fid] = parsed

    # 2) explicit runtime config file (overrides profile)
    for fid, value in file_features.items():
        if fid not in defs:
            config_errors.append(f"runtime config references unknown feature '{fid}'")
            continue
        parsed = _parse_bool(value if isinstance(value, bool) else None)
        if parsed is not None:
            enabled[fid] = parsed

    # 3) explicit runtime input (tests / scripts / experiment drivers)
    for fid, value in runtime_input.get("features", {}).items():
        if fid not in defs:
            config_errors.append(f"runtime input references unknown feature '{fid}'")
            continue
        if isinstance(value, bool):
            enabled[fid] = value

    # 4) env overrides (highest priority) — canonical names + aliases
    for f in registry["features"]:
        direct = _parse_bool(env.get(f["envRuntimeName"]))
        if direct is not None:
            enabled[f["id"]] = direct
    for env_name, ids in ENV_ALIASES.items():
        parsed = _parse_bool(env.get(env_name))
        if parsed is not None:
            for fid in ids:
                enabled[fid] = parsed

    experiment_id = (runtime_input.get("experimentId")
                     or (config_file.get("experimentId") if isinstance(config_file.get("experimentId"), str) else None)
                     or env.get("FEATURE_EXPERIMENT_ID")
                     or None)
    return RuntimeResolved(
        runtime_profile=profile_name,
        runtime_enabled=enabled,
        experiment_id=experiment_id,
        warnings=warnings,
        config_errors=config_errors,
    )


def get_commit_sha() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=Path(__file__).resolve().parents[3],
            capture_output=True, text=True, check=False, timeout=10,
        )
        return out.stdout.strip() or "unknown"
    except Exception:  # noqa: BLE001
        return "unknown"


class FeatureResolver:
    """Effective feature resolution — built once per process at startup."""

    def __init__(self,
                 registry: Optional[dict[str, Any]] = None,
                 build_manifest: Optional[dict[str, Any]] = None,
                 runtime: Optional[RuntimeResolved] = None,
                 env: Optional[dict[str, str]] = None) -> None:
        self.registry = registry if registry is not None else load_registry()
        self.build_manifest = build_manifest if build_manifest is not None else BUILD_FEATURE_MANIFEST
        self.env = os.environ if env is None else env
        self.runtime = runtime if runtime is not None else resolve_runtime_settings(self.registry, self.env)
        self.defs = {f["id"]: f for f in self.registry["features"]}
        self.strict = _parse_bool(self.env.get(STRICT_ENV)) or False
        self.eval_mode = _parse_bool(self.env.get(EVALUATION_MODE_ENV)) or False
        self.warnings: list[str] = list(self.runtime.warnings)

        if self.strict and self.runtime.config_errors:
            raise RuntimeError(
                "FEATURE_CONFIG_STRICT: invalid feature configuration — "
                + "; ".join(self.runtime.config_errors))
        self.warnings.extend(self.runtime.config_errors)

        self._assert_no_unsafe_in_production()
        self.states = self._compute_states()

    # -- construction guards ------------------------------------------------

    def _assert_no_unsafe_in_production(self) -> None:
        if self.env.get(APP_ENV_VAR) != "production":
            return
        built = [f["id"] for f in self.registry["features"]
                 if f["safetyClass"] == "unsafe" and self.build_manifest["buildEnabled"].get(f["id"])]
        requested = [f["id"] for f in self.registry["features"]
                     if f["safetyClass"] == "unsafe" and self.runtime.runtime_enabled.get(f["id"])]
        offenders = sorted(set(built) | set(requested))
        if offenders:
            raise RuntimeError(
                "APP_ENV=production with unsafe ablation(s) configured "
                f"({', '.join(offenders)}) — refusing to start. Unsafe ablations require "
                "BUILD_UNSAFE_EVALUATION_ABLATIONS=true, EVALUATION_MODE=true and "
                "APP_ENV != production.")

    def _compute_states(self) -> dict[str, FeatureState]:
        states: dict[str, FeatureState] = {}
        effective: dict[str, bool] = {}

        def dep_effective(dep: str) -> bool:
            """Effective state of a dependency, computed on demand (order
            independent — registry order may put a dependency after its user)."""
            if dep in states:
                return states[dep].effectiveEnabled
            f = self.defs.get(dep)
            if f is None:
                return False
            if not bool(self.build_manifest["buildEnabled"].get(dep)):
                return False
            if not bool(self.runtime.runtime_enabled.get(dep, f["runtimeDefault"])):
                return False
            if f["parent"] is not None and not dep_effective(f["parent"]):
                return False
            return all(dep_effective(d) for d in f["dependencies"])

        def parent_effective(fid: str) -> bool:
            f = self.defs[fid]
            build_ok = bool(self.build_manifest["buildEnabled"].get(fid))
            runtime_ok = bool(self.runtime.runtime_enabled.get(fid))
            if not build_ok or not runtime_ok:
                return False
            if f["parent"] is not None and not parent_effective(f["parent"]):
                return False
            return all(dep_effective(d) for d in f["dependencies"])

        for f in self.registry["features"]:
            fid = f["id"]
            build_enabled = bool(self.build_manifest["buildEnabled"].get(fid))
            requested = self.runtime.runtime_enabled.get(fid, f["runtimeDefault"])
            runtime_enabled = requested

            if f["safetyClass"] == "unsafe":
                if requested and not self.eval_mode:
                    runtime_enabled = False
                    self.warnings.append(
                        f"{fid}: unsafe ablation requested but EVALUATION_MODE is not true — "
                        "ineffective. Set EVALUATION_MODE=true (and APP_ENV != production) to enable.")
                elif requested and self.eval_mode:
                    self.warnings.append(
                        f"UNSAFE ABLATION ENABLED: {fid} (build: BUILD_UNSAFE_EVALUATION_ABLATIONS=true, "
                        "runtime: EVALUATION_MODE=true). Results must be marked unsafeAblation=true.")
                elif requested and self.env.get(UNSAFE_MASTER_BUILD_ENV) != "true":
                    self.warnings.append(f"{fid}: build manifest does not include unsafe ablations — not effective.")

            reason = None
            if not build_enabled:
                reason = "NOT_BUILT"
            elif not runtime_enabled:
                reason = "RUNTIME_DISABLED"
            else:
                parent_ok = f["parent"] is None or (states[f["parent"]].effectiveEnabled
                                                    if f["parent"] in states else parent_effective(f["parent"]))
                if not parent_ok:
                    reason = "PARENT_DISABLED"
                else:
                    dep_ok = all(dep_effective(d) for d in f["dependencies"])
                    if not dep_ok:
                        reason = "DEPENDENCY_DISABLED"

            is_effective = reason is None
            states[fid] = FeatureState(
                id=fid,
                buildEnabled=build_enabled,
                runtimeEnabled=runtime_enabled,
                effectiveEnabled=is_effective,
                disabledReason=reason,
                parent=f["parent"],
                dependencies=list(f["dependencies"]),
            )
            effective[fid] = is_effective
        return states

    # -- public API ----------------------------------------------------------

    def is_built(self, fid: str) -> bool:
        return fid in self.defs and bool(self.build_manifest["buildEnabled"].get(fid))

    def is_runtime_enabled(self, fid: str) -> bool:
        state = self.states.get(fid)
        return state is not None and state.runtimeEnabled

    def is_effective(self, fid: str) -> bool:
        state = self.states.get(fid)
        return state is not None and state.effectiveEnabled

    def require_feature(self, fid: str) -> None:
        state = self.states.get(fid)
        if state is None or not state.effectiveEnabled:
            reason = state.disabledReason if state else "UNKNOWN"
            raise RuntimeError(f"feature '{fid}' is not effective ({reason}).")

    def get_feature_state(self, fid: str) -> FeatureState:
        if fid not in self.states:
            raise KeyError(f"unknown feature id '{fid}'")
        return self.states[fid]

    def get_states(self) -> dict[str, FeatureState]:
        return dict(self.states)

    def get_build_manifest(self) -> dict[str, Any]:
        return self.build_manifest

    def get_runtime_profile(self) -> Optional[str]:
        return self.runtime.runtime_profile

    def get_warnings(self) -> list[str]:
        return list(self.warnings)

    def get_effective_feature_snapshot(self,
                                       runtime_input: Optional[dict[str, Any]] = None) -> FeatureSnapshot:
        runtime_input = runtime_input or {}
        states = self.get_states()
        effective = sorted(fid for fid, s in states.items() if s.effectiveEnabled)
        disabled = sorted(fid for fid, s in states.items() if not s.effectiveEnabled)
        unsafe = sorted(fid for fid, s in states.items()
                        if s.effectiveEnabled and self.defs[fid]["safetyClass"] == "unsafe")

        effective_states = {fid: states[fid].effectiveEnabled for fid in sorted(states)}
        runtime_hash = feature_hash({"profile": self.runtime.runtime_profile,
                                     "features": dict(self.runtime.runtime_enabled)})
        eff_hash = feature_hash({"features": effective_states})

        return FeatureSnapshot(
            experimentId=runtime_input.get("experimentId") or self.runtime.experiment_id,
            commitSha=get_commit_sha(),
            buildProfile=self.build_manifest["buildProfile"],
            buildFeatureHash=self.build_manifest["buildFeatureHash"],
            runtimeProfile=self.runtime.runtime_profile,
            runtimeFeatureHash=runtime_hash,
            effectiveFeatureHash=eff_hash,
            effectiveFeatures=effective,
            disabledFeatures=disabled,
            unsafeAblations=unsafe,
            modelId=runtime_input.get("modelId") or os.environ.get("MODEL_ID"),
            promptVersion=runtime_input.get("promptVersion") or os.environ.get("PROMPT_VERSION"),
            datasetSnapshot=runtime_input.get("datasetSnapshot") or os.environ.get("DATASET_SNAPSHOT"),
            randomSeed=runtime_input.get("randomSeed") or os.environ.get("RANDOM_SEED"),
            ruleVersion=runtime_input.get("ruleVersion") or os.environ.get("FEATURE_RULE_VERSION") or CDXR_RULE_VERSION,
            generatedAt=__import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
        )


def feature_summary_line(resolver: FeatureResolver) -> str:
    snap = resolver.get_effective_feature_snapshot()
    suffix = f" UNSAFE_ABLATIONS=[{', '.join(snap.unsafeAblations)}]" if snap.unsafeAblations else ""
    return (f"[features] profile={snap.buildProfile} effHash={snap.effectiveFeatureHash} "
            f"enabled=[{', '.join(snap.effectiveFeatures)}] "
            f"disabled=[{', '.join(snap.disabledFeatures)}]{suffix}")


_default_resolver: Optional[FeatureResolver] = None


def get_default_resolver() -> FeatureResolver:
    """Process-wide resolver — built once at first use (startup semantics)."""
    global _default_resolver
    if _default_resolver is None:
        _default_resolver = FeatureResolver()
    return _default_resolver


def _set_default_resolver(resolver: Optional[FeatureResolver]) -> None:
    """Test hook: replace the process-wide resolver (never used in prod paths)."""
    global _default_resolver
    _default_resolver = resolver


def _print(argv: list[str]) -> int:
    args = set(argv)
    resolver = get_default_resolver()
    snapshot = resolver.get_effective_feature_snapshot()
    if "--json" in args:
        print(json.dumps(snapshot.to_dict(), indent=2))
    else:
        print(feature_summary_line(resolver))
        for state in sorted(resolver.get_states().values(), key=lambda s: s.id):
            marker = "ON" if state.effectiveEnabled else f"OFF({state.disabledReason})"
            print(f"  {state.id:<34} build={str(state.buildEnabled):<5} "
                  f"runtime={str(state.runtimeEnabled):<5} -> {marker}")
        for warning in resolver.get_warnings():
            print(f"warning: {warning}")
    if "--write" in args:
        out = Path(__file__).resolve().parents[3] / "build" / "feature-snapshot.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(snapshot.to_dict(), indent=2) + "\n", encoding="utf-8")
        print(f"snapshot written to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(_print(sys.argv[1:]))
